- hosts: all
  become: True
  become_user: root
  vars:
    installation_dir : "/opt/hadoop"

  tasks:
    ##################################################################
    #SSH gakoak sortu eta elkarbanatzea faltako litzateke. Isardeko makinetan eginda dago
    ##################################################################

    - name:  Beharrezko direktorioa sortu
      become: yes
      file:
        path: "{{installation_dir}}"
        state: directory
        mode: 0755
        owner: hadoop
        group: hadoop

    - name: Log direktorioa sortu
      become: yes
      file:
        path: /tmp/logs
        state: directory
        mode: 1777
        
    - name: Hadoop lortu
      become: yes
      become_user: hadoop
      unarchive:
#        src: https://dlcdn.apache.org/hadoop/common/hadoop-3.4.1/hadoop-3.4.1.tar.gz
        src: https://dlcdn.apache.org/hadoop/common/hadoop-3.3.6/hadoop-3.3.6.tar.gz
        dest: "{{installation_dir}}"
        mode: 0755
        remote_src: yes

    - name: Move all the files to parent Directory
      become: yes
      become_user: hadoop
      shell: |
        mv {{installation_dir}}/hadoop-*/* {{installation_dir}}/.
        rm -r {{installation_dir}}/hadoop-*

    - name: profile fitxategia Hadoopen iturburuarekin eguneratu
      ansible.builtin.lineinfile:
        path: /home/hadoop/.profile
        regexp: '^PATH='
        line: 'PATH=/opt/hadoop/bin:/opt/hadoop/sbin:$PATH'
        owner: hadoop
        group: hadoop

    - name: bashrc fitxategian PATH egokitu
      ansible.builtin.lineinfile:
        path: /home/hadoop/.bashrc
        regexp: '^export HADOOP_HOME='
        line: 'export HADOOP_HOME=/opt/hadoop'
        owner: hadoop
        group: hadoop

    - name: bashrc fitxategian YARN_HOME egokitu
      ansible.builtin.lineinfile:
        path: /home/hadoop/.bashrc
        regexp: '^export YARN_HOME='
        line: 'export YARN_HOME=$HADOOP_HOME'
        owner: hadoop
        group: hadoop

    - name: bashrc fitxategian HADOOP COMMON LIB egokitu
      ansible.builtin.lineinfile:
        path: /home/hadoop/.bashrc
        regexp: '^export HADOOP_COMMON_LIB_NATIVE_DIR='
        line: 'export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native'
        owner: hadoop
        group: hadoop            

    - name: bashrc fitxategian HADOOP_OPTS LIB egokitu
      ansible.builtin.lineinfile:
        path: /home/hadoop/.bashrc
        regexp: '^export HADOOP_OPTS='
        line: 'export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib/native"'
        owner: hadoop
        group: hadoop            
        
    - name: bashrc fitxategian PATH egokitu
      ansible.builtin.lineinfile:
        path: /home/hadoop/.bashrc
        regexp: '^export PATH='
        line: 'export PATH=${PATH}:${HADOOP_HOME}/bin:${HADOOP_HOME}/sbin'
        owner: hadoop
        group: hadoop

    - name: "Fetch JAVA_HOME"
      shell: dirname $(dirname $(readlink -f $(which javac)))
      register: java_home

    - name: JAVA_HOME bashrc fitxategian
      ansible.builtin.lineinfile:
        path: /home/hadoop/.bashrc
        regexp: '^export JAVA_HOME='
        line: 'export JAVA_HOME={{ java_home.stdout }}'
        owner: hadoop
        group: hadoop
        
    - name: JAVA_HOME eguneratu hadoop instalazioan
      ansible.builtin.lineinfile:
        path: /opt/hadoop/etc/hadoop/hadoop-env.sh        
        regexp: '^export JAVA_HOME='
        line: 'export JAVA_HOME={{ java_home.stdout }}'
        owner: hadoop
        group: hadoop
    - name: JAVA_HOME eguneratu hadoop instalazioan
      ansible.builtin.lineinfile:
        path: /opt/hadoop/etc/hadoop/hadoop-env.sh        
        regexp: '^export HADOOP_CLASSPATH+='
        line: 'export HADOOP_CLASSPATH+=" $HADOOP_HOME/lib/*.jar"'
        owner: hadoop
        group: hadoop
    - name: hadoop-env HADOOP_OPTS
      ansible.builtin.lineinfile:
        path: /opt/hadoop/etc/hadoop/hadoop-env.sh        
        regexp: '^export HADOOP_OPTS='
        line: 'export HADOOP_OPTS="$HADOOP_OPTS --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED"'
        owner: hadoop
        group: hadoop


    - name: JAVA_HOME eguneratu hadoop instalazioan
      ansible.builtin.lineinfile:
        path: /opt/hadoop/etc/hadoop/hadoop-env.sh        
        regexp: '^export HADOOP_CLASSPATH+='
        line: 'export HADOOP_CLASSPATH+=" $HADOOP_HOME/lib/*.jar"'
        owner: hadoop
        group: hadoop

    - name: core-site.xml fitxategia kopiatu 
      ansible.builtin.template:
        src: template/core-site.xml.j2
        dest: /opt/hadoop/etc/hadoop/core-site.xml
        owner: hadoop
        group: hadoop
        mode: '0644'
    - name: hdfs-site.xml fitxategia kopiatu 
      ansible.builtin.template:
        src: template/hdfs-site.xml.j2
        dest: /opt/hadoop/etc/hadoop/hdfs-site.xml
        owner: hadoop
        group: hadoop
        mode: '0644'
    - name: mapred-site.xml fitxategia kopiatu 
      ansible.builtin.template:
        src: template/mapred-site.xml.j2
        dest: /opt/hadoop/etc/hadoop/mapred-site.xml
        owner: hadoop
        group: hadoop
        mode: '0644'                
    - name: yarn-site.xml fitxategia kopiatu 
      ansible.builtin.template:
        src: template/yarn-site.xml.j2
        dest: /opt/hadoop/etc/hadoop/yarn-site.xml
        owner: hadoop
        group: hadoop
        mode: '0644'
    - name: worker fitxategia datanodeekin
      ansible.builtin.template:
        src: template/workers.j2
        dest: /opt/hadoop/etc/hadoop/workers
        owner: hadoop
        group: hadoop
        mode: '0744'
    - name: masters fitxategia datanodeekin
      ansible.builtin.template:
        src: template/masters.j2
        dest: /opt/hadoop/etc/hadoop/masters
        owner: hadoop
        group: hadoop
        mode: '0744'                                
