- hosts: all
  become: True
  become_user: root

  tasks:
    - name: Sistema eguneratu
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
        
    - name: Eguneratu APT package manager repositories cache
      become: true
      apt:
        update_cache: yes
    - name: Istal Java using Ansible
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - default-jre
           - default-jdk
           - unzip
    - name: ACL instalatu (hadoop erabiltzaile bezala fitxategiak jaisteko beharrezkoa)
      become: yes
      apt:
        name: 
          - acl
        state: present
        update_cache: yes

    - name: Hadoop erabiltzailea sortu
      ansible.builtin.user:
        name: hadoop
        shell: /bin/bash
        create_home: yes

    - name: Sortu .ssh direktorioa hadoop erabiltzailean
      ansible.builtin.file:
        path: /home/hadoop/.ssh
        state: directory
      become: yes
      become_user: hadoop

      # Haul aldatzea komeniko litzateke. Momentuan gakoak sortu eta hedatu
    - name: kopiatu ir_inf erabiltzaileko hadoop_key hadoop erabiltzailera (remote-remote)
      ansible.builtin.copy:
        src: /home/ir_inf/.ssh/hadoop_key
        dest: /home/hadoop/.ssh/hadoop_key
        remote_src: yes
        owner: hadoop
        group: hadoop
        mode: '0600'
    - name: kopiatu ir_inf erabiltzaileko gako publikoa
      ansible.builtin.copy:
        src: /home/ir_inf/.ssh/authorized_keys
        dest: /home/hadoop/.ssh/authorized_keys
        remote_src: yes
        owner: hadoop
        group: hadoop
        mode: '0600'
