- hosts: all
  become: True
  become_user: root

  tasks:
    - name: Sistema eguneratu
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
        
    - name: Eguneratu APT package manager repositories cache
      become: true
      apt:
        update_cache: yes
    - name: Instal Java using Ansible
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - openjdk-17-jdk
           - unzip
    - name: ACL instalatu (hadoop erabiltzaile bezala fitxategiak jaisteko beharrezkoa)
      become: yes
      apt:
        name: 
          - acl
        state: present
        update_cache: yes

    - name: Hadoop erabiltzailea sortu
      ansible.builtin.user:
        name: hadoop
        shell: /bin/bash
        create_home: yes

    - name: Sortu .ssh direktorioa hadoop erabiltzailean
      ansible.builtin.file:
        path: /home/hadoop/.ssh
        state: directory
      become: yes
      become_user: hadoop
      
    # - name: Copy a "sudoers" file on the remote machine for editing
    #   ansible.builtin.copy:
    #     src: /home/ir_inf/.ssh/hadoop_key
    #     dest: /home/hadoop/.ssh/hadoop_key
    #     remote_src: yes

