- name: Exchange Keys between servers
  hosts: all
  become: True
  become_user: root
  tasks:
    - name: SSH KeyGen command
      become_user: hadoop
      tags: run
      shell: > 
        ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
        creates="~/.ssh/id_rsa"

    - name: Fetch the keyfile from the node to master
      become_user: hadoop      
      tags: run
      fetch: 
        src: "~/.ssh/id_rsa.pub"
        dest: "buffer/{{ansible_hostname}}-id_rsa.pub"
        flat: yes

    - name: Copy the key add to authorized_keys using Ansible module
      tags: runcd
      authorized_key:
        user: hadoop
        state: present
        key: "{{ lookup('file','buffer/{{item}}-id_rsa.pub')}}"
#      when: "{{ item != ansible_hostname }}"
      with_items: 
        - "{{ groups['all'] }}"       

    - name: ssh konfigurazio fitxategia
      ansible.builtin.template:
        src: template/ssh_config.j2
        dest: /home/hadoop/.ssh/config
        owner: hadoop
        group: hadoop
        mode: '0600'
        


